# Generated by Django 5.1.5 on 2025-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='searchitem',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
